### ISSUE TITLE
[PACE-15] Add apiVersion and kind to all YAML representations of Proto messages

### ISSUE THREAD

**Issue by trietsch** [getstrm/pace#24]
An example of a Data Policy that includes version and kind:

```yaml
apiVersion: pace.getstrm.com/v1alpha
kind: DataPolicy
metadata:
  name: "alpha_test.demo"
platform:
...
```

This would enable us to operate multiple different api versions simultaneously. This is a client side feature, as it currently is not embedded in the protos themselves, and the client should read the fields to determine the RPC to call and to determine whether the version is still supported.
Another option would be to include this in the protos and enforce this server side.

<sub>[PACE-15](https://linear.app/strmprivacy/issue/PACE-15/add-apiversion-and-kind-to-all-yaml-representations-of-proto-messages)</sub>
